
class KeyCode(object):
    KEYCODE_MENU = 1
    KEYCODE_HOME = 3
    KEYCODE_BACK = 4
    KEYCODE_DPAD_RIGHT = 22

    KEYCODE_A = 29

    KEYCODE_DEL = 67
    KEYCODE_ESCAPE = 111
    KEYCODE_MOVE_END = 123
    KEYCODE_CONTROL = 28672